export type MichiPhaseId = 'foundation_n5_n4' | 'bridge_n3' | 'academic_readiness_n2'

export interface MonthlyFocus {
  monthNumber: number
  phase: MichiPhaseId
  title: string
  jlptTarget: 'N5' | 'N4' | 'N3' | 'N2'
  languageGoals: string[]
  studySystems: string[]
  designAndJapanFocus: string[]
  adhdSupport: string[]
}

export const MICHI_TWO_YEAR_CURRICULUM: MonthlyFocus[] = [
  {
    monthNumber: 1,
    phase: 'foundation_n5_n4',
    title: 'Quiet re-entry and daily ritual building',
    jlptTarget: 'N5',
    languageGoals: ['kana fluency', 'core survival phrases', 'daily listening habit'],
    studySystems: ['5-12 minute sessions', 'micro review after each scene', 'one visible win per day'],
    designAndJapanFocus: ['Japan as future, not only fantasy', 'noticing places, light, signs, trains'],
    adhdSupport: ['very short tasks', 'clear finish lines', 'low-pressure restart logic'],
  },
  {
    monthNumber: 2,
    phase: 'foundation_n5_n4',
    title: 'Core sentence patterns and everyday reading',
    jlptTarget: 'N5',
    languageGoals: ['basic particles', 'simple self-expression', 'short notice reading'],
    studySystems: ['alternating text and audio', 'fast feedback', 'visual anchors'],
    designAndJapanFocus: ['object vocabulary', 'color and shape basics'],
    adhdSupport: ['choice between task types', 'reduced clutter', 'repeatable routine'],
  },
  {
    monthNumber: 3,
    phase: 'foundation_n5_n4',
    title: 'Movement through the city',
    jlptTarget: 'N5',
    languageGoals: ['transport language', 'time expressions', 'simple requests and directions'],
    studySystems: ['scene clusters', 'mini speaking prompts', 'micro dictation'],
    designAndJapanFocus: ['station typography', 'maps and symbols'],
    adhdSupport: ['novelty through scene rotation', 'predictable task length'],
  },
  {
    monthNumber: 4,
    phase: 'foundation_n5_n4',
    title: 'Home, food, shopping, comfort',
    jlptTarget: 'N4',
    languageGoals: ['daily routine verbs', 'shopping questions', 'simple comparisons'],
    studySystems: ['review loops', 'paired vocab + phrase cards', 'low-friction listening'],
    designAndJapanFocus: ['materials, textures, packaging'],
    adhdSupport: ['small chunks', 'external structure', 'positive reinforcement'],
  },
  {
    monthNumber: 5,
    phase: 'foundation_n5_n4',
    title: 'Talking about preferences and observations',
    jlptTarget: 'N4',
    languageGoals: ['describing what you like', 'basic reasons', 'linked short statements'],
    studySystems: ['guided output', 'reflection prompts', 'short retrieval practice'],
    designAndJapanFocus: ['describing favorite spaces and objects'],
    adhdSupport: ['gentle prompts', 'visual examples', 'limited cognitive load'],
  },
  {
    monthNumber: 6,
    phase: 'foundation_n5_n4',
    title: 'Reading simple explanations and notices',
    jlptTarget: 'N4',
    languageGoals: ['reading signs and short instructions', 'polite forms', 'basic contrast'],
    studySystems: ['notice-reading sets', 'mini quizzes', 'audio replay'],
    designAndJapanFocus: ['public information design', 'clarity and layout'],
    adhdSupport: ['timed tiny tasks', 'one-goal cards'],
  },
  {
    monthNumber: 7,
    phase: 'bridge_n3',
    title: 'Bridge into connected Japanese',
    jlptTarget: 'N4',
    languageGoals: ['longer connected sentences', 'cause/effect', 'routine narration'],
    studySystems: ['transfer cards', 'shadowing', 'pattern review'],
    designAndJapanFocus: ['process vocabulary', 'steps and user flow'],
    adhdSupport: ['explicit transitions', 'task previews'],
  },
  {
    monthNumber: 8,
    phase: 'bridge_n3',
    title: 'Functional listening in real environments',
    jlptTarget: 'N4',
    languageGoals: ['announcements', 'service interactions', 'simple problem solving'],
    studySystems: ['listen -> choose -> repeat', 'error-friendly retries'],
    designAndJapanFocus: ['wayfinding and environment cues'],
    adhdSupport: ['immediate feedback', 'short audio windows'],
  },
  {
    monthNumber: 9,
    phase: 'bridge_n3',
    title: 'Reading for purpose',
    jlptTarget: 'N3',
    languageGoals: ['extracting key info', 'short forms and messages', 'comparing options'],
    studySystems: ['scanning practice', 'guided annotation', 'focused review'],
    designAndJapanFocus: ['comparing posters, menus, layouts'],
    adhdSupport: ['highlighted key targets', 'reduced text density'],
  },
  {
    monthNumber: 10,
    phase: 'bridge_n3',
    title: 'Explaining choices and intentions',
    jlptTarget: 'N3',
    languageGoals: ['explaining why', 'stating plans', 'giving short opinions'],
    studySystems: ['sentence-building ladders', 'voice input prompts', 'mini reflection'],
    designAndJapanFocus: ['why this composition works', 'what feeling a design creates'],
    adhdSupport: ['multiple response modes', 'low shame correction'],
  },
  {
    monthNumber: 11,
    phase: 'bridge_n3',
    title: 'Early academic comprehension',
    jlptTarget: 'N3',
    languageGoals: ['classroom instructions', 'assignment words', 'note-taking basics'],
    studySystems: ['lecture fragments', 'keyword extraction', 'follow-up review'],
    designAndJapanFocus: ['studio/class language', 'assignment prompts'],
    adhdSupport: ['preview-recall cycle', 'small note chunks'],
  },
  {
    monthNumber: 12,
    phase: 'bridge_n3',
    title: 'End of year consolidation',
    jlptTarget: 'N3',
    languageGoals: ['integrated reading + listening', 'short paragraph output', 'repair strategies'],
    studySystems: ['mixed review weeks', 're-entry packs', 'adaptive recap'],
    designAndJapanFocus: ['portfolio and self-presentation basics'],
    adhdSupport: ['gentle catch-up mode', 'visible progress markers'],
  },
  {
    monthNumber: 13,
    phase: 'academic_readiness_n2',
    title: 'Shift into wider real Japanese',
    jlptTarget: 'N3',
    languageGoals: ['longer explanatory texts', 'contextual listening', 'richer connectors'],
    studySystems: ['text families', 'retrieval review', 'topic clusters'],
    designAndJapanFocus: ['design culture reading', 'craft and editorial language'],
    adhdSupport: ['structured variety', 'clear task sequencing'],
  },
  {
    monthNumber: 14,
    phase: 'academic_readiness_n2',
    title: 'Lecture-like comprehension and paraphrase',
    jlptTarget: 'N3',
    languageGoals: ['grasping main points', 'paraphrasing ideas', 'following spoken structure'],
    studySystems: ['listen -> outline -> recap', 'short synthesis tasks'],
    designAndJapanFocus: ['observing visual argument and intent'],
    adhdSupport: ['guided chunking', 'repeatable templates'],
  },
  {
    monthNumber: 15,
    phase: 'academic_readiness_n2',
    title: 'Critique language starter',
    jlptTarget: 'N2',
    languageGoals: ['describing strengths and weaknesses', 'gentle critique', 'comparison language'],
    studySystems: ['before/after analysis', 'sentence stems', 'peer-style prompts'],
    designAndJapanFocus: ['composition critique', 'type, balance, hierarchy'],
    adhdSupport: ['bounded response frames', 'no-blank-page tasks'],
  },
  {
    monthNumber: 16,
    phase: 'academic_readiness_n2',
    title: 'Reading longer articles and explainers',
    jlptTarget: 'N2',
    languageGoals: ['editorial reading', 'argument structure', 'topic summarising'],
    studySystems: ['section-by-section reading', 'summary cards', 'transfer prompts'],
    designAndJapanFocus: ['Japanese design essays and profiles'],
    adhdSupport: ['section goals', 'predictable reading flow'],
  },
  {
    monthNumber: 17,
    phase: 'academic_readiness_n2',
    title: 'Academic task language',
    jlptTarget: 'N2',
    languageGoals: ['report instructions', 'constraints and criteria', 'submission language'],
    studySystems: ['task decoding', 'instruction cards', 'mini response drills'],
    designAndJapanFocus: ['studio briefs', 'presentation prep'],
    adhdSupport: ['instruction parsing aids', 'checklists'],
  },
  {
    monthNumber: 18,
    phase: 'academic_readiness_n2',
    title: 'Presentation readiness',
    jlptTarget: 'N2',
    languageGoals: ['presenting decisions', 'signposting', 'handling short questions'],
    studySystems: ['micro presentations', 'recall scripts', 'confidence loops'],
    designAndJapanFocus: ['portfolio talk', 'why this solution fits the brief'],
    adhdSupport: ['short rehearsal units', 'script support'],
  },
  {
    monthNumber: 19,
    phase: 'academic_readiness_n2',
    title: 'Study in Japan practical language',
    jlptTarget: 'N2',
    languageGoals: ['forms, deadlines, housing, support services', 'reading official info', 'asking for help'],
    studySystems: ['reality cards', 'path scenarios', 'factual review'],
    designAndJapanFocus: ['university and faculty navigation'],
    adhdSupport: ['decision support scaffolds', 'structured next-step prompts'],
  },
  {
    monthNumber: 20,
    phase: 'academic_readiness_n2',
    title: 'Higher listening tolerance',
    jlptTarget: 'N2',
    languageGoals: ['faster speech tolerance', 'extracting gist under uncertainty', 'repair and re-listen habits'],
    studySystems: ['layered listening', 'gist-first method', 'confidence protection'],
    designAndJapanFocus: ['talks, interviews, studio explanations'],
    adhdSupport: ['reduced penalty for misses', 'guided replay'],
  },
  {
    monthNumber: 21,
    phase: 'academic_readiness_n2',
    title: 'Integrated design + academic communication',
    jlptTarget: 'N2',
    languageGoals: ['combining critique, explanation, and reflection', 'context-sensitive vocabulary'],
    studySystems: ['integrated tasks', 'compare-and-defend prompts'],
    designAndJapanFocus: ['process explanation and revision logic'],
    adhdSupport: ['fixed response structures', 'manageable complexity'],
  },
  {
    monthNumber: 22,
    phase: 'academic_readiness_n2',
    title: 'N2-style consolidation',
    jlptTarget: 'N2',
    languageGoals: ['reading stamina', 'listening stamina', 'precision under pressure'],
    studySystems: ['spiral review', 'adaptive weak-area packs', 'small mock sets'],
    designAndJapanFocus: ['portfolio and faculty-facing self-description'],
    adhdSupport: ['micro mocks', 'planned breaks'],
  },
  {
    monthNumber: 23,
    phase: 'academic_readiness_n2',
    title: 'Pre-university readiness',
    jlptTarget: 'N2',
    languageGoals: ['handling study materials', 'following task instructions', 'asking clarifying questions'],
    studySystems: ['study simulation weeks', 'functional task chains'],
    designAndJapanFocus: ['studio critique and classroom participation'],
    adhdSupport: ['external structure', 'supportive prompts'],
  },
  {
    monthNumber: 24,
    phase: 'academic_readiness_n2',
    title: 'Quiet final integration',
    jlptTarget: 'N2',
    languageGoals: ['stable reading/listening routines', 'practical self-expression', 'academic survival readiness'],
    studySystems: ['capstone review', 're-entry-safe maintenance mode', 'personal weak-area loops'],
    designAndJapanFocus: ['future-in-Japan narrative and design trajectory'],
    adhdSupport: ['maintenance without burnout', 'clear next-step paths'],
  },
]

export default MICHI_TWO_YEAR_CURRICULUM
