export interface AcademicJapaneseCard {
  id: string
  title: string
  jlptBand: 'N4' | 'N3' | 'N2'
  category: 'instruction' | 'lecture' | 'note_taking' | 'assignment' | 'discussion' | 'presentation'
  situation: string
  focus: string[]
  usefulPatterns: string[]
  microTask: string
  designContext?: string
  adhdSupport: string[]
}

const academicJapaneseCards: AcademicJapaneseCard[] = [
  {
    id: 'academic_001',
    title: 'Understanding simple classroom instructions',
    jlptBand: 'N4',
    category: 'instruction',
    situation: 'A teacher explains what to prepare before the next class.',
    focus: ['instruction verbs', 'time reference', 'what to bring'],
    usefulPatterns: ['〜までに', '〜を持ってきてください', '〜を読んでおいてください'],
    microTask: 'Rewrite the instruction as 3 simple action steps.',
    adhdSupport: ['convert speech into checklist', 'action-first framing', '3-step cap'],
  },
  {
    id: 'academic_002',
    title: 'Short note-taking from a tiny explanation',
    jlptBand: 'N4',
    category: 'note_taking',
    situation: 'You hear a short explanation about a task in class.',
    focus: ['keyword capture', 'what matters now', 'what is optional'],
    usefulPatterns: ['まず', 'つぎに', 'だいじなのは', 'あとで'],
    microTask: 'Make a note with only 4 keywords, then explain the task in your own words.',
    adhdSupport: ['reduced writing load', 'keyword limit', 'decode before full output'],
  },
  {
    id: 'academic_003',
    title: 'Reading assignment prompts without panic',
    jlptBand: 'N4',
    category: 'assignment',
    situation: 'You receive a short assignment description with a deadline.',
    focus: ['deadline language', 'submission language', 'task constraints'],
    usefulPatterns: ['提出', '締め切り', '〜について', '〜字以内'],
    microTask: 'Answer: what is the task, when is it due, and what is the limit?',
    adhdSupport: ['3-question decode frame', 'separate task from deadline', 'clear extraction target'],
  },
  {
    id: 'academic_004',
    title: 'Following the structure of a mini lecture',
    jlptBand: 'N3',
    category: 'lecture',
    situation: 'A teacher gives a short explanation with an example and conclusion.',
    focus: ['main point', 'example spotting', 'conclusion markers'],
    usefulPatterns: ['たとえば', 'つまり', 'このように', 'ポイントは'],
    microTask: 'Split the lecture into topic / example / point.',
    adhdSupport: ['fixed listening scaffold', 'structure over full transcription', 'small capture template'],
  },
  {
    id: 'academic_005',
    title: 'Joining a classroom discussion softly',
    jlptBand: 'N3',
    category: 'discussion',
    situation: 'You want to add an idea without sounding too strong.',
    focus: ['soft opinion language', 'agreement/disagreement', 'adding to others'],
    usefulPatterns: ['たしかに', '一方で', '私は〜と思います', '少し〜かもしれません'],
    microTask: 'Write one soft agreement and one soft disagreement sentence.',
    adhdSupport: ['sentence stems', 'social safety through soft phrasing', 'two-sentence cap'],
  },
  {
    id: 'academic_006',
    title: 'Explaining your process in simple academic Japanese',
    jlptBand: 'N3',
    category: 'presentation',
    situation: 'You need to explain how you approached a task step by step.',
    focus: ['sequence language', 'decision explanation', 'cause and result'],
    usefulPatterns: ['最初に', 'そのあとで', 'そのため', '結果として'],
    microTask: 'Explain one small study or design process in 4 linked steps.',
    designContext: 'Useful for early studio explanations and design process talk.',
    adhdSupport: ['4-step structure', 'bounded explanation', 'process-first framing'],
  },
  {
    id: 'academic_007',
    title: 'Finding the key sentence in a study text',
    jlptBand: 'N3',
    category: 'lecture',
    situation: 'You read a short study-related text and need the central idea fast.',
    focus: ['topic sentence', 'supporting detail vs main idea', 'summary skill'],
    usefulPatterns: ['〜という', '重要なのは', '中心となる', '要するに'],
    microTask: 'Choose one central sentence and justify why it matters.',
    adhdSupport: ['main-idea targeting', 'single-sentence goal', 'reduced overload'],
  },
  {
    id: 'academic_008',
    title: 'Handling classroom clarification questions',
    jlptBand: 'N3',
    category: 'discussion',
    situation: 'You did not fully understand and need to ask without freezing.',
    focus: ['clarification requests', 'repetition requests', 'checking understanding'],
    usefulPatterns: ['もう一度お願いします', '〜という意味ですか', 'ここはどういうことですか'],
    microTask: 'Build 3 real clarification questions you could actually use.',
    adhdSupport: ['real survival phrases', 'permission to ask', 'high utility'],
  },
  {
    id: 'academic_009',
    title: 'Reading for comparison and choice',
    jlptBand: 'N3',
    category: 'assignment',
    situation: 'You compare two study options, references, or approaches.',
    focus: ['comparison markers', 'advantages / disadvantages', 'decision language'],
    usefulPatterns: ['〜に対して', 'その一方で', 'メリット', 'デメリット'],
    microTask: 'Compare two options and state which one is better for your goal.',
    adhdSupport: ['choice architecture', 'two-option constraint', 'reason prompt'],
  },
  {
    id: 'academic_010',
    title: 'Decoding rubric-like criteria',
    jlptBand: 'N2',
    category: 'assignment',
    situation: 'A teacher explains what a good submission should include.',
    focus: ['criteria language', 'evaluation words', 'required components'],
    usefulPatterns: ['評価', '観点', '明確さ', '根拠', '一貫性'],
    microTask: 'Turn the criteria into a self-check list before submission.',
    adhdSupport: ['external checklist', 'criteria translation', 'submission safety'],
  },
  {
    id: 'academic_011',
    title: 'Listening for argument flow',
    jlptBand: 'N2',
    category: 'lecture',
    situation: 'You hear a more complex explanation with multiple parts and a conclusion.',
    focus: ['argument structure', 'contrast', 'conclusion signals'],
    usefulPatterns: ['しかし', 'そのうえで', 'したがって', '結論として'],
    microTask: 'Map the talk as claim / support / contrast / conclusion.',
    adhdSupport: ['argument map template', 'structure-first listening', 'replay-friendly framing'],
  },
  {
    id: 'academic_012',
    title: 'Seminar response: summarise and react',
    jlptBand: 'N2',
    category: 'discussion',
    situation: 'You need to react to someone else’s explanation in a seminar-like setting.',
    focus: ['summary + response pattern', 'agreeing with nuance', 'adding a thought'],
    usefulPatterns: ['つまり〜ということですね', 'その点は共感します', 'ただ、私は'],
    microTask: 'Write a 3-part response: summary, reaction, added thought.',
    adhdSupport: ['three-part interaction frame', 'social clarity', 'bounded response'],
  },
  {
    id: 'academic_013',
    title: 'Presentation signposting for design and study',
    jlptBand: 'N2',
    category: 'presentation',
    situation: 'You present a project, process, or analysis in front of others.',
    focus: ['signposting', 'transition language', 'audience guidance'],
    usefulPatterns: ['まず〜を見てください', '次に', 'ここで注目したいのは', '最後に'],
    microTask: 'Build a 60-second mini presentation outline with spoken transitions.',
    designContext: 'Useful for portfolio reviews, studio explanations, and project walkthroughs.',
    adhdSupport: ['signpost template', 'low-memory structure', 'audience guidance cues'],
  },
  {
    id: 'academic_014',
    title: 'Reading institutional information without getting lost',
    jlptBand: 'N2',
    category: 'instruction',
    situation: 'You read a university page about procedures, support, or deadlines.',
    focus: ['official wording', 'procedural order', 'must vs optional'],
    usefulPatterns: ['必要があります', '対象者', '手続き', '該当する場合'],
    microTask: 'Extract: who is this for, what must be done, and by when?',
    adhdSupport: ['3-part extraction rule', 'official-language decoding', 'priority filtering'],
  },
  {
    id: 'academic_015',
    title: 'Explaining a design decision academically',
    jlptBand: 'N2',
    category: 'presentation',
    situation: 'You need to explain not only what looks good, but why the choice works.',
    focus: ['rationale language', 'effect on user/viewer', 'constraint-aware explanation'],
    usefulPatterns: ['意図としては', '〜を強調するために', '見やすさ', '一貫性'],
    microTask: 'Explain one design decision using intention -> method -> effect.',
    designContext: 'Directly supports critique, studio talk, and portfolio explanation in Japanese.',
    adhdSupport: ['3-part rationale frame', 'no blank-page problem', 'high relevance to design goal'],
  },
]

export default academicJapaneseCards
