export type TransferCardTrack = 'journey_japanese' | 'live_in_japan' | 'study_in_japan' | 'design_in_japanese' | 'michi_expression'

export interface TransferCard {
  id: string
  title: string
  track: TransferCardTrack
  jlptBand: 'N5' | 'N4' | 'N3' | 'N2'
  sourceSkill: string
  transferTask: string
  outputMode: 'speak' | 'write' | 'notice' | 'plan' | 'compare'
  supportPrompt: string
  adhdSupport: string[]
}

const transferCards: TransferCard[] = [
  {
    id: 'transfer_001',
    title: 'From station scene to real route choice',
    track: 'live_in_japan',
    jlptBand: 'N5',
    sourceSkill: 'transport vocabulary and direction words',
    transferTask: 'Choose between two train routes and explain which one is easier for you.',
    outputMode: 'speak',
    supportPrompt: 'Start with: こっちのほうが… because…',
    adhdSupport: ['two-option choice', 'clear sentence starter', 'short spoken output'],
  },
  {
    id: 'transfer_002',
    title: 'From café scene to a tiny real order',
    track: 'live_in_japan',
    jlptBand: 'N5',
    sourceSkill: 'food words and polite requests',
    transferTask: 'Create one simple café order for a drink and a dessert.',
    outputMode: 'speak',
    supportPrompt: 'Use one full request, not a vocabulary list.',
    adhdSupport: ['micro output', 'bounded task', 'single success target'],
  },
  {
    id: 'transfer_003',
    title: 'From room scene to describing your study corner',
    track: 'michi_expression',
    jlptBand: 'N5',
    sourceSkill: 'basic location and object language',
    transferTask: 'Describe where 3 objects are in your room or on your desk.',
    outputMode: 'write',
    supportPrompt: 'Pattern: A は B の うえ / した / となり に あります',
    adhdSupport: ['repeatable template', 'three-item limit', 'visual grounding'],
  },
  {
    id: 'transfer_004',
    title: 'From shopping scene to comparing two options',
    track: 'live_in_japan',
    jlptBand: 'N4',
    sourceSkill: 'adjectives and simple comparison patterns',
    transferTask: 'Compare two bags, two notebooks, or two cafés and say which one you would choose.',
    outputMode: 'compare',
    supportPrompt: 'Use at least one reason, not only “I like it”.',
    adhdSupport: ['real-world objects', 'choice structure', 'reason prompt'],
  },
  {
    id: 'transfer_005',
    title: 'From notice reading to real sign decoding',
    track: 'study_in_japan',
    jlptBand: 'N4',
    sourceSkill: 'short notice reading',
    transferTask: 'Read a short sign or instruction and answer: what must I do now?',
    outputMode: 'notice',
    supportPrompt: 'Answer in one clear action sentence.',
    adhdSupport: ['single concrete question', 'action-first framing', 'reduced ambiguity'],
  },
  {
    id: 'transfer_006',
    title: 'From daily scene to mini schedule plan',
    track: 'study_in_japan',
    jlptBand: 'N4',
    sourceSkill: 'time expressions and routine verbs',
    transferTask: 'Make a tiny after-school schedule with 3 steps.',
    outputMode: 'plan',
    supportPrompt: 'Use time + action + one connector.',
    adhdSupport: ['3-step cap', 'external structure', 'predictable layout'],
  },
  {
    id: 'transfer_007',
    title: 'From observation scene to “why I like this place”',
    track: 'michi_expression',
    jlptBand: 'N4',
    sourceSkill: 'preference language and simple reasons',
    transferTask: 'Write 2–3 lines on why a station, café, bridge, or street feels good to you.',
    outputMode: 'write',
    supportPrompt: 'Move from image -> feeling -> reason.',
    adhdSupport: ['small emotional frame', 'short output', 'guided order'],
  },
  {
    id: 'transfer_008',
    title: 'From “Path to Japan” card to a next-step choice',
    track: 'study_in_japan',
    jlptBand: 'N4',
    sourceSkill: 'practical vocabulary around study plans',
    transferTask: 'Choose one next step: language school, university research, housing, or scholarship search — and explain why it is first.',
    outputMode: 'plan',
    supportPrompt: 'One next step is enough. Do not plan the whole life at once.',
    adhdSupport: ['one-step framing', 'decision support', 'reduced overwhelm'],
  },
  {
    id: 'transfer_009',
    title: 'From map scene to a micro navigation task',
    track: 'live_in_japan',
    jlptBand: 'N4',
    sourceSkill: 'map words and direction language',
    transferTask: 'Explain how to go from the station to a café, library, or river.',
    outputMode: 'speak',
    supportPrompt: 'Keep it to 3–4 directions only.',
    adhdSupport: ['limited step count', 'spatial anchor', 'short sequence'],
  },
  {
    id: 'transfer_010',
    title: 'From design vocabulary to object description',
    track: 'design_in_japanese',
    jlptBand: 'N4',
    sourceSkill: 'shape, color, texture basics',
    transferTask: 'Describe one poster, package, chair, or notebook using 3 design words.',
    outputMode: 'write',
    supportPrompt: 'Focus on what you can clearly see, not on theory.',
    adhdSupport: ['concrete visual target', '3-word cap', 'low abstraction'],
  },
  {
    id: 'transfer_011',
    title: 'From N4 reading to choosing key information',
    track: 'study_in_japan',
    jlptBand: 'N3',
    sourceSkill: 'extracting important information from short texts',
    transferTask: 'Read a short practical text and highlight the 2 most important facts for action.',
    outputMode: 'notice',
    supportPrompt: 'Ask yourself: what would go wrong if I miss this?',
    adhdSupport: ['priority filter', 'two-item limit', 'functional focus'],
  },
  {
    id: 'transfer_012',
    title: 'From scene feeling to mini spoken reflection',
    track: 'michi_expression',
    jlptBand: 'N3',
    sourceSkill: 'connected short speaking',
    transferTask: 'Speak for 30–45 seconds about a place that helps you feel calm and why.',
    outputMode: 'speak',
    supportPrompt: 'Use a simple beginning, middle, and ending.',
    adhdSupport: ['time-bounded speaking', 'clear arc', 'emotionally safe prompt'],
  },
  {
    id: 'transfer_013',
    title: 'From class instruction language to task decoding',
    track: 'study_in_japan',
    jlptBand: 'N3',
    sourceSkill: 'assignment and instruction words',
    transferTask: 'Rewrite a classroom instruction in your own simpler Japanese or Russian.',
    outputMode: 'write',
    supportPrompt: 'The goal is understanding, not elegant wording.',
    adhdSupport: ['decode before perform', 'permission to simplify', 'clarity over style'],
  },
  {
    id: 'transfer_014',
    title: 'From design observation to first critique language',
    track: 'design_in_japanese',
    jlptBand: 'N3',
    sourceSkill: 'soft critique starters',
    transferTask: 'Say one thing that works well in a layout and one thing that feels slightly weak.',
    outputMode: 'compare',
    supportPrompt: 'Use gentle wording. Think “works / could be clearer”, not harsh judgment.',
    adhdSupport: ['two-part frame', 'soft language guardrail', 'reduced perfectionism'],
  },
  {
    id: 'transfer_015',
    title: 'From article reading to summary sentence chain',
    track: 'study_in_japan',
    jlptBand: 'N3',
    sourceSkill: 'following longer connected text',
    transferTask: 'Turn a short article into 3 linked summary sentences.',
    outputMode: 'write',
    supportPrompt: 'Sentence 1: topic. Sentence 2: key point. Sentence 3: why it matters.',
    adhdSupport: ['fixed summary frame', '3-sentence cap', 'compression support'],
  },
  {
    id: 'transfer_016',
    title: 'From reality card to survival question',
    track: 'study_in_japan',
    jlptBand: 'N2',
    sourceSkill: 'practical academic/life vocabulary',
    transferTask: 'Form one real help-seeking question about housing, deadlines, forms, or support services.',
    outputMode: 'speak',
    supportPrompt: 'Imagine you really need this answer tomorrow.',
    adhdSupport: ['realistic urgency', 'single-question goal', 'functional communication'],
  },
  {
    id: 'transfer_017',
    title: 'From lecture fragment to note skeleton',
    track: 'study_in_japan',
    jlptBand: 'N2',
    sourceSkill: 'academic listening and keyword extraction',
    transferTask: 'Listen or read a short lecture fragment and produce a 3-part note skeleton: topic / point / example.',
    outputMode: 'plan',
    supportPrompt: 'Do not write full sentences unless needed.',
    adhdSupport: ['note template', 'reduced writing load', 'structured capture'],
  },
  {
    id: 'transfer_018',
    title: 'From design track to portfolio explanation',
    track: 'design_in_japanese',
    jlptBand: 'N2',
    sourceSkill: 'presentation and explanation language',
    transferTask: 'Explain one design decision in a portfolio piece: what you changed, why you changed it, and what effect you wanted.',
    outputMode: 'speak',
    supportPrompt: 'Use a simple 3-step structure instead of trying to sound advanced.',
    adhdSupport: ['three-part speaking frame', 'real design relevance', 'low-pressure structure'],
  },
]

export default transferCards
