export type PathCategory = 'grants' | 'language' | 'university' | 'visa' | 'daily_life' | 'design' | 'community'
export type Horizon = 'now' | 'one_year' | 'long_term'

export interface PathCard {
  id: string
  category: PathCategory
  horizon: Horizon
  title: string
  summary: string
  practical_tip: string
  small_step: string
  official_link?: string
  michi_note: string
}

const pathCards: PathCard[] = [
  { id: 'lang_1', category: 'language', horizon: 'now', title: 'JLPT: как понимать уровни', summary: 'JLPT имеет пять уровней от N5 до N1. По официальному описанию N4 и N5 проверяют в основном базовый японский, изучаемый в классе; N1 и N2 — японский, используемый в широком диапазоне реальных жизненных ситуаций; N3 — мост между ними.', practical_tip: 'Для Michi это значит: нельзя останавливаться на «красивых сценах». Нужны ежедневные сцены + повторение + аудирование + академический язык.', small_step: 'Открой официальный summary JLPT и сохрани себе описание N2 и N3.', official_link: 'https://www.jlpt.jp/e/about/levelsummary.html', michi_note: 'N2 — это уже не просто «понимать урок». Это чувствовать ритм реальной японской среды.' },
  { id: 'lang_2', category: 'language', horizon: 'one_year', title: 'Что проверяет EJU по японскому', summary: 'Официально EJU проверяет японский, необходимый для высшего образования и повседневной жизни в Японии. Экзамен включает comprehension (reading, listening, listening & reading) и writing.', practical_tip: 'Если цель — учиться в японском университете, одной JLPT-логики мало. В контенте обязательно нужны: чтение, слушание, работа с визуальной информацией, письмо и краткие академические ответы.', small_step: 'Открой syllabus EJU Japanese as a Foreign Language и посмотри, что там проверяется кроме чтения.', official_link: 'https://www.jasso.go.jp/en/ryugaku/eju/examinee/syllabus/japanese.html', michi_note: 'Университет любит не только знания, но и умение быстро ориентироваться в форме задания.' },
  { id: 'uni_1', category: 'university', horizon: 'long_term', title: 'Study in Japan: главный официальный вход', summary: 'Портал Study in Japan от JASSO — один из самых надёжных стартовых источников для поиска информации об учёбе, программах и поступлении.', practical_tip: 'Для Michi этот ресурс должен быть базовым ориентиром, когда пользователь начинает думать уже не о мечте, а о маршруте поступления.', small_step: 'Сохрани портал в закладки и найди раздел про поиск учебных заведений.', official_link: 'https://www.studyinjapan.go.jp/en/', michi_note: 'Иногда большой путь начинается не с чемодана, а с правильной закладки в браузере.' },
  { id: 'uni_2', category: 'university', horizon: 'one_year', title: 'EJU нужен не всем, но очень многим', summary: 'JASSO прямо указывает, что EJU используется для оценки, хватает ли международному абитуриенту японского и базовых академических навыков для учёбы в японском вузе. Конкретные требования задаёт сам университет.', practical_tip: 'Значит, Michi должен готовить не «в среднем», а учить пользователя проверять требования конкретной программы.', small_step: 'Открой список школ, использующих EJU, когда дойдёшь до этапа выбора университетов.', official_link: 'https://www.jasso.go.jp/en/ryugaku/eju/about/about_a/about_eju.html', michi_note: 'Университеты редко любят угадывание. Они любят точное чтение требований.' },
  { id: 'design_1', category: 'design', horizon: 'long_term', title: 'Как учат visual communication design', summary: 'Официальное описание Musashino Art University показывает важную логику: от базовых элементов композиции, формы, цвета и типографики — к работе с разными медиа, визуальной информацией, редактированием и specialised practice.', practical_tip: 'Поэтому в Michi нужен отдельный трек Design in Japanese: форма, цвет, typography, layout, information, critique, concept, user, material, space.', small_step: 'Прочитай outline Visual Communication Design и выпиши 10 дизайнерских слов, которые тебе хочется уметь говорить по-японски.', official_link: 'https://www.musabi.ac.jp/english/course/undergraduate/vcd/', michi_note: 'Дизайн — это не только смотреть. Это ещё и уметь объяснить, почему ты сделал именно так.' },
  { id: 'design_2', category: 'design', horizon: 'one_year', title: 'Чему учат на первых курсах дизайна', summary: 'На официальной странице curriculum Musashino VCD описаны: first year — базовая формообразующая работа и совместные проекты; second year — техники, media, связь пространства и времени; later years — information design, environmental design, package design, illustration, CG, video.', practical_tip: 'Это хороший ориентир, какой дизайнерский язык нужно встроить в Michi уже на N4/N3, а какой оставить на продвинутый этап.', small_step: 'Сохрани для себя 3 направления: typography / information / space — они могут стать твоими будущими любимыми словами на японском.', official_link: 'https://www.musabi.ac.jp/english/course/undergraduate/vcd/curriculum/', michi_note: 'Хороший дизайн редко начинается с финального макета. Обычно он начинается с внимательного первого курса.' },
  { id: 'study_1', category: 'university', horizon: 'now', title: 'Нужно учить язык для лекций, а не только для тестов', summary: 'По syllabus EJU Japanese as a Foreign Language проверяются reading, listening, listening & reading и writing — именно как язык для высшего образования и жизни.', practical_tip: 'Значит, каждую неделю в Michi должны быть не только scene + words, но и short note-taking, summary, instruction reading, audio-style tasks и короткие письменные ответы.', small_step: 'В своей подготовке раздели занятия на 4 корзины: reading / listening / writing / speaking.', official_link: 'https://www.jasso.go.jp/en/ryugaku/eju/examinee/syllabus/japanese.html', michi_note: 'Экзамен любит целостность. И язык тоже.' },
  { id: 'daily_1', category: 'daily_life', horizon: 'now', title: 'Учёба = жизнь + язык', summary: 'Комфортное обучение в Японии требует не только аудиторного языка, но и языка повседневной жизни: транспорт, жильё, покупки, просьбы, дедлайны, объявления.', practical_tip: 'Поэтому в Michi нельзя отделять «бытовой японский» от «академического японского». Пользователь будет жить и учиться одновременно.', small_step: 'Собери свой первый словарь из 20 слов по теме station / classroom / café / deadline.', michi_note: 'Язык помогает не только понимать лекцию, но и не потеряться по дороге на неё.' },
  { id: 'grants_1', category: 'grants', horizon: 'long_term', title: 'Стипендии и финансирование: начинать с официальных источников', summary: 'Если пользователь идёт к реальному поступлению, все данные о стипендиях и финансировании нужно брать только с официальных и регулярно обновляемых источников.', practical_tip: 'Не вшивай в статический контент быстро устаревающие суммы, сроки и обещания. Для этого лучше использовать карточки с официальными ссылками и отдельный AI/web layer.', small_step: 'Сохрани раздел scholarships на Study in Japan и проверяй его, когда подойдёшь ближе к подаче.', official_link: 'https://www.studyinjapan.go.jp/en/planning/scholarships/', michi_note: 'Мечта любит поэзию. Документы любят точность. Им обоим нужно место.' },
  { id: 'community_1', category: 'community', horizon: 'one_year', title: 'Учиться легче, когда есть контекст', summary: 'Для удержания и роста полезно не только учить слова, но и видеть, где они живут: в заданиях, афишах, станциях, интерфейсах, кафе, музеях и мастерских.', practical_tip: 'Поэтому контент Michi должен регулярно соединять сцену, жизненную ситуацию и учебную пользу.', small_step: 'Выбери 1 визуальный мир — station, river, sakura, design studio — и копи слова именно вокруг него.', michi_note: 'Слова запоминаются лучше, когда у них есть улица, свет и история.' },
  { id: 'visa_1', category: 'visa', horizon: 'long_term', title: 'Процесс важнее догадок', summary: 'Визовые и поступательные шаги лучше строить как process-based path: изучить требования программы → проверить язык и экзамены → собрать документы → следовать официальным инструкциям.', practical_tip: 'Для статического контента лучше давать не цифры и обещания, а безопасную последовательность шагов и официальные ссылки.', small_step: 'Сделай себе личную карту процесса: language → exam → university → documents.', official_link: 'https://www.studyinjapan.go.jp/en/', michi_note: 'Большой путь становится легче, когда превращается в последовательность маленьких правильных шагов.' },

  { id: 'design_3', category: 'design', horizon: 'long_term', title: 'Critique language: нужно уметь не только чувствовать, но и объяснять', summary: 'Для реальной учёбы на дизайне в Японии понадобится язык для описания композиции, выбора формы, пользовательского опыта, референсов и итераций.', practical_tip: 'В продукте нужен отдельный набор micro-cards: composition, contrast, material, layout, prototype, feedback, revision.', small_step: 'Собери себе мини-набор из 5 слов: composition, typography, material, concept, prototype.', michi_note: 'Хорошая идея становится сильнее, когда ты умеешь назвать, почему она работает.' },
  { id: 'study_2', category: 'university', horizon: 'one_year', title: 'Нужен язык не только для теста, но и для заданий', summary: 'Путь к учёбе в Японии включает лексику инструкций, дедлайнов, заметок, коротких summary и classroom communication.', practical_tip: 'Это значит, что Study in Japan track должен регулярно давать instructions, mini writing и task language.', small_step: 'Добавь в свою неделю 1 маленький summary на 3–4 предложения.', michi_note: 'Язык учёбы — это язык движения, а не только правильных ответов.' },
  { id: 'grants_2', category: 'grants', horizon: 'one_year', title: 'Стипендии стоит воспринимать как исследование, а не как обещание', summary: 'Для Michi безопаснее давать структуру поиска и official links, чем хранить внутри продукта быстро устаревающие суммы и даты.', practical_tip: 'Path to Japan должен учить пользователя проверять условия конкретного года и конкретной программы.', small_step: 'Составь себе чек-лист: источник, дата обновления, требования, язык, сроки.', official_link: 'https://www.studyinjapan.go.jp/en/planning/scholarships/', michi_note: 'Надёжность редко выглядит ярко. Но именно она проводит дальше.' },
]

export default pathCards

export function getCardsForUser(interests: PathCategory[] = [], shownIds: string[] = [], preferredHorizon?: Horizon): PathCard[] {
  const unseen = pathCards.filter(card => !shownIds.includes(card.id))
  const interestBoosted = unseen.sort((a, b) => {
    const ai = interests.includes(a.category) ? 1 : 0
    const bi = interests.includes(b.category) ? 1 : 0
    const ah = preferredHorizon && a.horizon === preferredHorizon ? 1 : 0
    const bh = preferredHorizon && b.horizon === preferredHorizon ? 1 : 0
    return (bi + bh) - (ai + ah)
  })
  return interestBoosted.slice(0, 6)
}
